docker:
  es_host: localhost
  es_port: 9200
  es_index: articles

test:
  es_host: test_localhost
  es_port: 9200
  es_index: test_articles

dev:
  es_host: <dev-cluster>
  es_port: 443

prod:
  es_host: <prod-cluster>
  es_port: 443

